services:

    blog_bundle.event.listener.entity.remove.blog:
        class: BlogBundle\EventListener\EntityListener\Remove\BlogEntityRemoveEventListener
        tags:
            - { name: kernel.event_listener, event: blog_bundle.event.entity_remove.blog, method: onEntityRemove }
              
    blog_bundle.event.listener.entity.remove.comment:
        class: BlogBundle\EventListener\EntityListener\Remove\CommentEntityRemoveEventListener
        tags:
            - { name: kernel.event_listener, event: blog_bundle.event.entity_remove.comment, method: onEntityRemove }
             
    blog_bundle.event.listener.entity.remove.post:
        class: BlogBundle\EventListener\EntityListener\Remove\PostEntityRemoveEventListener
        tags:
            - { name: kernel.event_listener, event: blog_bundle.event.entity_remove.post, method: onEntityRemove }
             
    blog_bundle.event.listener.entity.remove.user:
        class: BlogBundle\EventListener\EntityListener\Remove\UserEntityRemoveEventListener
        tags:
            - { name: kernel.event_listener, event: blog_bundle.event.entity_remove.user, method: onEntityRemove }
             
    blog_bundle.event.listener.entity.remove.user.profile:
        class: BlogBundle\EventListener\EntityListener\Remove\UserProfileEntityRemoveEventListener
        tags:
            - { name: kernel.event_listener, event: blog_bundle.event.entity_remove.userprofile, method: onEntityRemove }
             