services:

    blog_bundle.event.listener.entity.create.blog:
        class: BlogBundle\EventListener\EntityListener\Create\BlogEntityCreateEventListener
        tags:
            - { name:  kernel.event_listener, event: blog_bundle.event.entity_create.blog, method: onEntityCreate }

    blog_bundle.event.listener.entity.create.comment:
        class: BlogBundle\EventListener\EntityListener\Create\CommentEntityCreateEventListener
        tags:
            - { name:  kernel.event_listener, event: blog_bundle.event.entity_create.comment, method: onEntityCreate }

    blog_bundle.event.listener.entity.create.post:
        class: BlogBundle\EventListener\EntityListener\Create\PostEntityCreateEventListener
        tags:
            - { name:  kernel.event_listener, event: blog_bundle.event.entity_create.post, method: onEntityCreate }

    blog_bundle.event.listener.entity.create.user:
        class: BlogBundle\EventListener\EntityListener\Create\UserEntityCreateEventListener
        tags:
            - { name:  kernel.event_listener, event: blog_bundle.event.entity_create.user, method: onEntityCreate }

    blog_bundle.event.listener.entity.create.user.profile:
        class: BlogBundle\EventListener\EntityListener\Create\UserProfileEntityCreateEventListener
        tags:
            - { name:  kernel.event_listener, event: blog_bundle.event.entity_create.userprofile, method: onEntityCreate }
