BlogBundle\Entity\AbstractEntity:
  type: mappedSuperclass
#  entityListener:
#    BlogBundle\Event\EventListener\DoctrineEventListener\DoctrineEntityEventListener:
#      preFlush: [preFlushHandler]
#      postLoad: [postLoadHandler]
#
#      postPersist: [postPersistHandler]
#      prePersist: [prePersistHandler]
#
#      postUpdate: [postUpdateHandler]
#      preUpdate: [preUpdateHandler]
#
#      postRemove: [postRemoveHandler]
#      preRemove: [preRemoveHandler]
  id:
      id:
          type: guid
          generator:
              strategy: AUTO
  fields:
      createdAt:
          type: datetime
          nullable: false
          column: created_at
      updatedAt:
          type: datetime
          nullable: false
          column: updated_at