BlogBundle\Entity\Blog:
  type: entity
  table: bb_blog
  repositoryClass: BlogBundle\Entity\EntityRepository\Doctrine\BlogRepository
  fields:
      name:
          type: string
          length: 100
          nullable: false
      status:
          type: string
          length: 10
          nullable: false
  manyToOne:
      user:
          targetEntity: BlogBundle\Entity\User
          joinColumn:
              name: user_id
              referencedColumnName: id
  oneToMany:
      posts:
          targetEntity: BlogBundle\Entity\Post
          mappedBy: blog
          orderBy: { 'createdAt': 'ASC' }
          cascade:
              - remove
  lifecycleCallbacks:
      prePersist: [setCreatedAtValue, setUpdatedAtValue]
      preUpdate: [setUpdatedAtValue]
