BlogBundle\Entity\Comment:
  type: entity
  table: bb_comment
  repositoryClass: BlogBundle\Entity\EntityRepository\Doctrine\CommentRepository
  id:
      id:
          type: guid
          generator:
              strategy: AUTO
  fields:
      content:
          type: string
          nullable: false
          length: 2048
      status:
          type: string
          nullable: false
          length: 10
      createdAt:
          type: datetime
          nullable: false
          column: created_at
      updatedAt:
          type: datetime
          nullable: false
          column: updated_at
  manyToOne:
      user:
          targetEntity: BlogBundle\Entity\User
          joinColumn:
              name: user_id
              referencedColumnName: id
      post:
          targetEntity: BlogBundle\Entity\Post
          joinColumn:
              name: user_id
              referencedColumnName: id
      parent:
          targetEntity: BlogBundle\Entity\Comment
          inversedBy: children
          joinColumn:
              name: parent_id
              referencedColumnName: id
  oneToMany:
      children:
          targetEntity: BlogBundle\Entity\Comment
          mappedBy: parent
#      lifecycleCallbacks:
#          prePersist: [setCreatedAtValue, setUpdatedAtValue]
#          preUpdate: [setUpdatedAtValue]
