BlogBundle\Entity\Post:
  type: entity
  table: bb_post
  repositoryClass: BlogBundle\EntityManagement\EntityRepository\Doctrine\PostRepository
  fields:
      name:
          type: string
          length: 100
          nullable: false
      content:
          type: text
          nullable: false
      status:
          type: string
          length: 10
          nullable: false
  manyToOne:
      user:
          targetEntity: BlogBundle\Entity\User
          joinColumn:
              name: user_id
              referencedColumnName: id
      blog:
          targetEntity: BlogBundle\Entity\Blog
          inversedBy: posts
          joinColumn:
              name: blog_id
              referencedColumnName: id
  oneToMany:
      comments:
          targetEntity: BlogBundle\Entity\Comment
          mappedBy: post
          orderBy: {'createdAt': 'ASC'}

  lifecycleCallbacks:
      prePersist: [setCreatedAtValue, setUpdatedAtValue]
      preUpdate: [setUpdatedAtValue]