BlogBundle\Entity\User:
  type: entity
  table: bb_user
  repositoryClass: BlogBundle\EntityManagement\EntityRepository\Doctrine\UserRepository
  fields:
      username:
          type: string
          length: 100
          nullable: false
      password:
          type: string
          length: 64
          nullable: false
      lastLogin:
          type: datetime
          column: last_login
          nullable: true
      roles:
          type: array
      status:
          type: string
          length: 10
          nullable: false
  oneToOne:
      userProfile:
          targetEntity: BlogBundle\Entity\UserProfile
          mappedBy: user
          cascade:
              - persist
              - remove

  lifecycleCallbacks:
      prePersist: [setCreatedAtValue, setUpdatedAtValue]
      preUpdate: [setUpdatedAtValue]
