services:

    blog_bundle.blog.doctrine.repository:
        class: BlogBundle\EntityManagement\EntityRepository\Doctrine\BlogRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - BlogBundle\Entity\Blog

    blog_bundle.comment.doctrine.repository:
        class: BlogBundle\EntityManagement\EntityRepository\Doctrine\CommentRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - BlogBundle\Entity\Comment

    blog_bundle.post.doctrine.repository:
        class: BlogBundle\EntityManagement\EntityRepository\Doctrine\PostRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - BlogBundle\Entity\Post

    blog_bundle.user.doctrine.repository:
        class: BlogBundle\EntityManagement\EntityRepository\Doctrine\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - BlogBundle\Entity\User

    blog_bundle.user.profile.doctrine.repository:
        class: BlogBundle\EntityManagement\EntityRepository\Doctrine\UserProfileRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - BlogBundle\Entity\UserProfile